services:
  mongodb:
    image: mongo:7
    container_name: fleetdash-mongodb
    ports:
      - "27017:27017"
    volumes:
      - fleetdash_mongo:/data/db

  redis:
    image: redis:7
    container_name: fleetdash-redis
    ports:
      - "6379:6379"

volumes:
  fleetdash_mongo: